### ISSUE TITLE
zipalign not found

### ISSUE THREAD

**Issue by Amrkamel1** [fastphat/android-container#20]
Amazing job and very useful

But I have an issue I was trying to use the emulator and load and apk fike through appium that running on the same container but I keep getting this issue 

```
[[Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not find 'zipalign' in ["/opt/android/platform-tools/zipalign","/opt/android/emulator/zipalign","/opt/android/tools/zipalign","/opt/android/tools/bin/zipalign"]. Do you have Android Build Tools installed at '/opt/android'?]
]
```
not sure whats the problem it occurs only when I use Jenkins pipeline, if I run everything locally copy the apk to container /opt directory and launch my test its working fine 

but when I use Jenkins pipeline with same commands i got the error above

**Comment by fastphat** [comment]
`zipalign` is under `build-tools;20.0.0` (Android SDK Build Tools 20) so you will need to install that package with `sdkmanager`

- run docker container with bash
```docker run --privileged -it codecaigicungduoc/android-container:1.0 bash```

- install android build-tool sdk version 20
```yes Y | sdkmanager --verbose --no_https "build-tools;20.0.0"```

- check again and set path for that executed file. it is located under in `/opt/android/build-tools/20.0.0`
![image](https://user-images.githubusercontent.com/11498224/78890437-de7f0600-7a8f-11ea-84f7-bba8cd63369b.png)

- commit your change with `docker commit`

**Comment by Amrkamel1** [comment]
yes you were right, it has been resolved thx man
