### ISSUE TITLE
Running as root without --no-sandbox is not supported.

### ISSUE THREAD

**Issue by entwildfire** [fastphat/android-container#4]
Hi, sorry if my problem not related, but if you can help me plz.
When i build my docker by copy the emulator file in #1, I have an initialized device. So i can increase the boot time by snapshot like when using android studio. But when i try using this feature i get this error on exit (i get the result on the ubuntu on VM as root (like ubuntu in docker)):
```
emulator: Saving state on exit with session uptime 15645 ms
[8566:8566:0201/214339.170588:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```
Any idea how can i fix it?
Thanks

**Comment by fastphat** [comment]
can you share the full adb command that you used to run emulator with snapshot?

**Comment by entwildfire** [comment]
Auto snapshot not work as root user. I fix it by save manual snapshot and now the boot speed is just a few seconds.

1- Run emulator with same config in start.sh file.
2- Connect to the emulator console using `telnet localhost <port_name>` (for device 'emulator-5554' the port is 5554)
3- In emulator console: `auth <auth_token>` (auth token is in `/root/.emulator_console_auth_token`)
4- Save snapshot using `avd snapshot save <name>`
5- Copy `/root/.android` dir to build docker using this
6- In start.sh add `-snapshot <name>` to emulator parameters 
7- Build image using Dockerfile in #1 
For more details about emulator console: https://developer.android.com/studio/run/emulator-console

Thank you @fastphat for your help and support

**Comment by fastphat** [comment]
the container is wiped out after the process so you will technically have to cache the avd snapshot on local disk for latter restore. 

I am glad to see your question and see you've made it work (again)
